### ISSUE TITLE
HDR content not playing in HDR mode

### ISSUE THREAD

**Issue by Rajackar** [Moonfin-Client/WebOS#8]
While testing on G4 HDR content doesn't engage the HDR mode of the TV. Content plays with wahsed out colors.
Tested with HDR10 and DoVi, result is the same.
I'd be happy to provide more information and specific media info is needed.

**Comment by RadicalMuffinMan** [comment]
This is resolved in the latest release: [v2.0.0](https://github.com/Moonfin-Client/WebOS/releases/tag/2.0.0), please go check it out.

**Comment by angsanley** [comment]
I'm on 2.0.1 and HDR/DV still doesn't work. Perhaps any settings I should change?

**Comment by RadicalMuffinMan** [comment]
@angsanley I made some updates and would appreciate it if you could test:

Updated codecs and device specific capabilities
Added 'Force Direct Play' setting and enhance playback method handling

- Introduced a new setting to force Direct Play, bypassing codec checks.
- Updated the playback method determination to utilize the new setting.
- Updated the Player component to reflect the new forceDirectPlay option.

[org.moonfin.webos_2.0.1_all.zip](https://github.com/user-attachments/files/25143677/org.moonfin.webos_2.0.1_all.zip)

**Comment by Rajackar** [comment]
I might be stupid but I really can't find that setting.
I still have some playback issues but I noticed on the server dashboard that it's transcoding with the following reason:
"The video's bitrate exceeds the limit."
I've double checked the settigns and it's not set to a limit in the moonfinclient.
Official jellyfin client plays fine in this case.
(on a side note, the version in the client still displays 2.0)

**Comment by RadicalMuffinMan** [comment]
If you downloaded the file above the its in the playback setting

<img width="1163" height="736" alt="Image" src="https://github.com/user-attachments/assets/80a75d61-7f2f-47ad-8fa0-6ba2e655f060" />

**Comment by Rajackar** [comment]
I get both HDR 10 and dobly vision to play now. Seems to work well.
